### PR TITLE
letting domain and long arrow

### PR DESCRIPTION
**Pull request by N-J-Martin**

### CODE REVIEW

**Comment by N-J-Martin** [comment]
do you have any ideas about how to get the unnamed type bit working? or should I just leave it?  might bring it up on Monday...

**Comment by hz66-404** [comment]
let me have a look, btw do you think the "letting" keyword can share the notebook with this "letting domain"?

**Comment by N-J-Martin** [comment]
the notebook is quite large already so I wouldn't extend it much further but it could be linked to in Letting.md

**Comment by N-J-Martin** [comment]
I'm going to leave it as it is for now. If you could take a look @hz66-404, would be great! thanks :)

**Comment by hz66-404** [comment]
it looks awesome!! small question what about the unnamed part just leave it?

**Comment by N-J-Martin** [comment]
yh I couldn't get a way to displayit properly, and kind of just said that that was the point of the type existing here.

**Comment by hz66-404** [comment]
ok I see! well done!

**Pull request merged**
